name: Push

on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint Go Code
        uses: golangci/golangci-lint-action@v2
        with:
          args: --enable revive,unparam,misspell

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Execute local tests
        run: go test -v -coverprofile=cover.out -cover ./...

      - name: Generate coverage report
        run: go tool cover -html=cover.out -o coverage.html

      - name: Upload code coverage report
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report-${{ matrix.go }}
          path: coverage.html

  docker:
    name: Docker related stuff
    runs-on: ubuntu-latest
    needs: [lint, test]
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: BUILD_DATE=${{ steps.date.outputs.date }},VCS_REF=${{ github.sha }}
          tags: |
            ghcr.io/skynewz/template:${{ github.sha }}
            ghcr.io/skynewz/template:latest
